### ISSUE TITLE
NPM Run Start Issue

### ISSUE THREAD

**Issue by dryuvrajk** [OssamaLouati/Legal-AI_Project#3]
C:\Users\LegalAI-master\LegalAI-master\src>npm run start

> legal-ai@0.0.0 start
> ng serve

(node:29180) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:29180) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 3/4 modules 1 active …server\client\index.js?http://0.0.0.0:0node:internal/crypto/hash:80
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\LegalAI-master\LegalAI-master\node_modules\webpack\lib\util\createHash.js:75:53)
    at NormalModule._initBuildHash (C:\Users\LegalAI-master\LegalAI-master\node_modules\webpack\lib\NormalModule.js:339:16)
    at handleParseError (C:\Users\LegalAI-master\LegalAI-master\node_modules\webpack\lib\NormalModule.js:387:10)
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\webpack\lib\NormalModule.js:419:5
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\webpack\lib\NormalModule.js:280:12
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Users\LegalAI-master\LegalAI-master\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at Array.<anonymous> (C:\Users\LegalAI-master\LegalAI-master\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\Users\LegalAI-master\LegalAI-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.12.2

**Comment by OssamaLouati** [comment]
Fixed

**Comment by zeweihan** [comment]
Interesting project! Multilingual legal document processing is a real challenge — legal terminology varies significantly across jurisdictions even within the same language.

We're working on [AI Workdeck](https://github.com/zeweihan/aiworkdeck) — an open-source AI workspace specifically designed for legal teams. Our approach to multilingual legal docs involves:

- OCR pipeline with legal-specific preprocessing (stamps, watermarks, handwritten annotations)
- Clause-level extraction with jurisdiction-aware parsing
- Evidence chain tracking with full audit trails (critical for cross-border legal work)
- MCP-based agent orchestration so different legal AI tools can work together on the same document

Would be great to compare notes on handling multilingual legal text — especially for Asian legal systems where the document structure is quite different from Western formats.
