### ISSUE TITLE
NPM Run Build Issue

### ISSUE THREAD

**Issue by dryuvrajk** [OssamaLouati/Legal-AI_Project#4]
C:\Users\LegalAI-master\LegalAI-master\src>npm run build

> legal-ai@0.0.0 build
> ng build

 10% building modules 3/5 modules 2 active …-master\LegalAI-master\src\polyfills.tsC:\Users\LegalAI-master\LegalAI-master\node_modules\loader-runner\lib\LoaderRunner.js:106
                        throw new Error("callback(): The callback was already called.");
                              ^

Error: callback(): The callback was already called.
    at context.callback (C:\Users\LegalAI-master\LegalAI-master\node_modules\loader-runner\lib\LoaderRunner.js:106:10)
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\@ngtools\webpack\src\loader.js:91:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.12.2

**Comment by OssamaLouati** [comment]
Fixed
