### ISSUE TITLE
NPM Test

### ISSUE THREAD

**Issue by dryuvrajk** [OssamaLouati/Legal-AI_Project#5]
C:\Users\LegalAI-master\LegalAI-master\src>npm test

> legal-ai@0.0.0 test
> ng test

 10% building modules 1/1 modules 0 active(node:24912) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
02 05 2024 15:29:50.162:WARN [karma]: No captured browser, open http://localhost:9876/
02 05 2024 15:29:50.179:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
02 05 2024 15:29:50.179:INFO [launcher]: Launching browser Chrome with unlimited concurrency
02 05 2024 15:29:50.185:INFO [launcher]: Starting browser Chrome
 10% building modules 1/3 modules 2 active …-master\LegalAI-master\src\polyfills.ts02 05 2024 15:30:50.203:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
02 05 2024 15:30:52.219:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
02 05 2024 15:30:54.227:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing.
Terminate batch job (Y/N)? Error: callback(): The callback was already called.
    at context.callback (C:\Users\LegalAI-master\LegalAI-master\node_modules\loader-runner\lib\LoaderRunner.js:106:10)
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:104:7
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: callback(): The callback was already called.
    at context.callback (C:\Users\LegalAI-master\LegalAI-master\node_modules\loader-runner\lib\LoaderRunner.js:106:10)
    at C:\Users\LegalAI-master\LegalAI-master\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:104:7
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

^C

**Comment by OssamaLouati** [comment]
Fixed
